### ISSUE TITLE
Mainline changes to MCP2515?

### ISSUE THREAD

**Issue by adamvoss** [collin80/SW_CAN#1]
The current code base of this library is based on [macchina/mcp2515](https://github.com/macchina/mcp2515).  I restored this relationship in history so changes would be more apparent and have since split the changes made into single commits for each general change.  The result can be found at:  https://github.com/macchina-dev/SW_CAN/tree/swcan

Could you assist by providing details if any/all of these changes should be submitted back to the mcp2515 repository?  I somewhat wonder if the commit to rename the library and the commit to rename the Frame struct were omitted whether it could all be merged.

**Comment by collin80** [comment]
The changes are all relevant to the base MCP2515 library with the exceptions you listed. I renamed the library because it had the SWCAN additions and those aren't relevant. Also, I hadn't done thorough checking (as you have) to make sure that nothing else had changed. I didn't create the single wire additions you find in that file, I think one of the Macchina guys did.

If those were broken out to a separate file then there's no reason the rest of it couldn't be merged back to the base MCP2515 library. It would be a good idea to merge it all back together and then create a separate small single wire CAN library that implements the additional functionality required for single wire CAN.

**Comment by adamvoss** [comment]
Thanks for looking into this!

Since the bit for single wire CAN still is targeting the same MCP2515 library, would there be value in keeping the single-wire CAN functionality as part of it or is it definitely best as its own, dependent library?

**Comment by collin80** [comment]
I'd move all the single wire related code to a new dependent library and keep MCP2515 pure.

**Comment by adamvoss** [comment]
Thanks for your help with this!  The changes were merged by https://github.com/macchina/mcp2515/pull/7.

Splitting SW_CAN to its own dependent library is still unfinished (in testing), but closing this issue since this issue is not about that.
